%% LShape: 
% IGA-FEM
evaluate_data(3, 8, 2, ...
                '../out/lshape/lshape_ac/', ...
                'img_out/lshape_iga',...
                'full', ...
                'median');


% Standard-FEM
evaluate_data(3, 7, 1, '../out/lshape_standard/lshape_ac/', 'img_out/lshape_standard');

% Standard-FEM without neumann data on error estimator
evaluate_data(1, 5, 1, ...
                '../out/lshape_standard_no_nc/lshape_ac/', ...
                'img_out/lshape_standard_no_nc_p15', ...
                'lower_half', ...
                'median');
evaluate_data(3, 7, 1, ...
                '../out/lshape_standard_no_nc/lshape_ac/', ...
                'img_out/lshape_standard_no_nc_p37',...
                'lower_half');


%% Poisson_Neumann

% IGA-FEM without neumann data on error estimator
evaluate_data(2, 6, ...                                         % Load problem pmin to pmax
                2, ...                                          % Skip every second level
                '../out/poisson_neumann_adaptive/', ...         % problem folder
                'img_out/iga_fem_poisson_p26', ...              % output to
                'full', ...                      ider all points for reference
                'end' ...                                       % Attach reference line to the end
                );
%% 
% Standard FEM 
evaluate_data(2, 6, ...                                         % Load problem pmin to pmax
                1, ...                                          % Take every error level
                '../out/poisson_neumann_standard_no_nc/', ...   % problem folder
                'img_out/standard_fem_poisson_p26', ...         % Output to
                'full', ...                                     % Consider all points for reference
                'end' ...                                       % Attach reference line to the end
            );
        

%% Linear elasticity
evaluate_data(2, 7, ...
               2, ...
               '../out/linear_elasticity_inhomogeneous/2d/', ...
               'img_out/iga_fem_linear_elasticity_2d_p27', ...
               'full', ...
               'end' ...
               );
 
%% Line elast 3D 
evaluate_data(2, 2, ...
               3, ...
               '../out/linear_elasticity_inhomogeneous/3d/', ...
               'img_out/iga_fem_linear_elasticity_3d_p22', ...
               'full', ...
               'median', ...
               3 ...
               );        

%% Poisson Benchmark
evaluate_data(2, 2, ...
                3, ...
                '../out/poisson_benchmark_3d/', ...
                './img_out/iga_fem_poisson_benchmark_3d_p22', ...
                'full', ...
                'end',...
                3 ...
                );
            
%% Beam
pmin = 2; pmax = 2;
evaluate_data(pmin, pmax, ...
                3, ...
                '../out/beam/', ...
                ['./img_out/iga_fem_beam_p' num2str(pmin) num2str(pmax)], ...
                'full', ...
                'median',...
                3 ...
                );
           
%% Slab
pmin = 2; pmax = 2;
evaluate_data(pmin, pmax, ...
                3, ...
                '../out/slab/', ...
                ['./img_out/iga_fem_slab_p' num2str(pmin) num2str(pmax)], ...
                'full', ...
                'end',...
                3 ...
                );